### ISSUE TITLE
[BUG] data usage is shown incorrectly from time to time

### ISSUE THREAD

**Issue by yogifrog** [stickpin/homeassistant-meinvodafone#6]
## Before you post a new issue - you must first check the following (and check the boxes with an "X" below)
- [X] 1.) Can you login to MeinVodafone using the smartphone app or vodafone.de website?
- [X] 2.) I do not have 2FA enabled.

## Environment

- homeassistant-meinvodafone release with the issue:
- v1.1.4 and Previous
- Last working homeassistant-meinvodafone release (if known):
- Occurred in all versions so far
- Home Assistant Core release with the issue:
- I Use Core Version 2024.6.3
- Have you verified if MeinVodafone app or Website is working for you?:
- Yes

## Describe the bug
 from time to time the consumption is displayed as 25.600GB

## Steps to Reproduce
 Happens by itself without any recognizable pattern

## Screenshots
 Here you can see what Happens from Time to Time
![image](https://github.com/user-attachments/assets/22ff2d79-faf9-453c-ae6c-234895cf0382)

## Traceback/Error logs

```txt

```

## Note
Issues lacking sufficient details or context may be subject to closure without prior notice. Detailed bug reports are essential for effective issue resolution. Thank you for your cooperation.

**Comment by stickpin** [comment]
That's correct. It's an issue on Vodafone's side.
From time to time they report in kilobytes instead of megabytes.
If you open an original MeinVodafone app you will see the same behavior.
Maybe I will introduce some sort of protection for such a use case to avoid those peaks.

**Comment by yogifrog** [comment]
I haven't seen this in the MeinVodafone app (Android) yet, but it's good to know. Unfortunately, the ramp icon is missing under developer tools/statistics to correct this by hand. Is it possible to have this in a later version?

**Comment by stickpin** [comment]
not sure how to do it, but i will look at it once you will come back from vacation. :)

**Comment by yogifrog** [comment]
Thanks.

**Comment by stickpin** [comment]
please keep the issue open, I will close it after implementation. :)

**Comment by yogifrog** [comment]
I'm still new to Github and thought this could be closed for now. :)
